### ISSUE TITLE
Unexpected insert result with multiple data

### ISSUE THREAD

**Issue by qijianjun** [pwwang/pymedoo#3]
Hi, I try to insert multiple lines but got unexpected result, the columns messed up. the code the result is as below:
```
#!coding: utf-8
from medoo import Medoo

db = Medoo(dbtype="sqlite", database="test.db")
db.query('''create table table_1
    (id integer primary key,
    name varchar not null default "",
    category varchar not null default "",
    foo1 varchar not null default "",
    bar1 varchar not null default "",
    slug varchar not null default "",
    parent varchar not null default "",
    website varchar not null default "",
    theme boolean not null default 0,
    plugin boolean not null default 0,
    applycnt int not null default 0,
    ctime int not null default 0
    );''')
data = [
    {u'category': 1, 'website': u'Vannesa', 'bar1': u'Kym', u'name': u'Adrianna', 'parent': u'Rod', 'applycnt': 1, u'plugin': 1, 'ctime': 1557943085, 'id': 306, 'theme': 0, 'slug': '', u'foo1': u'Else'},
    {u'category': 1, 'website': u'Pilar', 'bar1': u'Carolann', u'name': u'Laci', 'parent': u'Aura', 'applycnt': 1, u'plugin': 1, 'ctime': 1557943085, 'id': 307, 'theme': 0, 'slug': '', u'foo1': u'Miss'},
    {u'category': 1, 'website': u'Cassi', 'bar1': u'Kareem', u'name': u'Florine', 'parent': u'Kathern', 'applycnt': 1, u'plugin': 1, 'ctime': 1557943085, 'id': 308, 'theme': 0, 'slug': '', u'foo1': u'Pilar'},
    {u'category': 1, 'website': u'Efrain', 'bar1': u'Seema', u'name': u'Chang', 'parent': u'Irish', 'applycnt': 1, u'plugin': 1, 'ctime': 1557943103, 'id': 309, 'theme': 0, 'slug': '', u'foo1': u'Breana'},
    {u'category': 1, 'website': u'Chery', 'bar1': u'Gilbert', u'name': u'Valentine', 'parent': u'Myesha', 'applycnt': 1, u'plugin': 1, 'ctime': 1557943103, 'id': 310, 'theme': 0, 'slug': '', u'foo1': u'Teri'},
    {u'category': 10, 'website': u'Fumiko', 'bar1': u'Debrah', u'name': u'Ranee', 'parent': '', 'plugin': 0, 'ctime': 1557929121, 'id': 1, 'theme': 0, 'applycnt': 1, 'slug': u'Merlin', u'foo1': u'Hershel'},
    {u'category': 23, 'website': u'Yolonda', 'bar1': u'Ava', u'name': u'Genoveva', 'parent': '', 'plugin': 0, 'ctime': 1557929121, 'id': 2, 'theme': 0, 'applycnt': 1, 'slug': u'Lavinia', u'foo1': u'Bev'},
    {u'category': 15, 'website': u'Angeline', 'bar1': u'Stephenie', u'name': u'Faye', 'parent': '', 'plugin': 0, 'ctime': 1557929121, 'id': 3, 'theme': 0, 'applycnt': 1, 'slug': u'Brianne', u'foo1': u'Milagro'},
    {u'category': 12, 'website': u'Leonia', 'bar1': u'Kaitlin', u'name': u'Whitley', 'parent': '', 'plugin': 0, 'ctime': 1557929121, 'id': 4, 'theme': 0, 'applycnt': 1, 'slug': u'Jesse', u'foo1': u'Denver'},
    {u'category': 27, 'website': u'Onie', 'bar1': u'Sondra', u'name': u'Jordon', 'parent': '', 'plugin': 0, 'ctime': 1557929138, 'id': 5, 'theme': 0, 'applycnt': 1, 'slug': u'Taisha', u'foo1': u'Roberto'},
    {u'category': 1, 'website': u'Dwana', 'bar1': u'Sheree', u'name': u'Bobbi', 'parent': '', 'plugin': 0, 'ctime': 1557929138, 'id': 6, 'theme': 0, 'applycnt': 1, 'slug': u'Leia', u'foo1': u'Birgit'},
    {u'category': 1, 'website': u'Sandra', 'bar1': u'Dirk', u'name': u'Gregory', 'parent': u'Ashly', 'plugin': 0, 'ctime': 1557929138, 'id': 7, u'theme': 1, 'applycnt': 1, 'slug': '', u'foo1': u'Walter'},
]
db.insert('table_1', *data)

```
![image](https://user-images.githubusercontent.com/612912/59211600-ce359a80-8be2-11e9-9bdd-b5d325024372.png)

If I change the column `theme`  to 'bl1', then I got a `sqlite3.IntegrityError: UNIQUE constraint failed: table_1.id:` error.

```
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    db.insert('table_1', *data)
  File "C:\Develop\Python27\lib\site-packages\medoo\base.py", line 70, in insert
    return self.query(sql, kwargs.get('commit', True))
  File "C:\Develop\Python27\lib\site-packages\medoo\base.py", line 113, in query
    raise type(ex)(str(ex) + ':\n' + self.sql)
sqlite3.IntegrityError: UNIQUE constraint failed: table_1.id:
INSERT INTO "table_1" ("website","bar1","parent","slug","ctime","category","name","plugin","bl1","id","applycnt","foo1") VALUES ('Vannesa','Kym','Rod','',1557943085,1,'Adrianna',1,0,306,1,'Else'),('Pilar','Carolann','Aura','',1557943085,1,'Laci',1,0,307,1,'Miss'),('Cassi','Kareem','Kathern','',1557943085,1,'Florine',1,0,308,1,'Pilar'),('Efrain','Seema','Irish','',1557943103,1,'Chang',1,0,309,1,'Breana'),('Chery','Gilbert','Myesha','',1557943103,1,'Valentine',1,0,310,1,'Teri'),('Fumiko','Debrah','',1,1,1557929121,10,'Ranee',0,0,'Merlin','Hershel'),('Yolonda','Ava','',2,1,1557929121,23,'Genoveva',0,0,'Lavinia','Bev'),('Angeline','Stephenie','',3,1,1557929121,15,'Faye',0,0,'Brianne','Milagro'),('Leonia','Kaitlin','',4,1,1557929121,12,'Whitley',0,0,'Jesse','Denver'),('Onie','Sondra','',5,1,1557929138,27,'Jordon',0,0,'Taisha','Roberto'),('Dwana','Sheree','',6,1,1557929138,1,'Bobbi',0,0,'Leia','Birgit'),('Sandra','Dirk','Ashly',7,1,1557929138,1,'Gregory',0,1,'','Walter')
```

**Comment by pwwang** [comment]
Thanks for pointing out this.
Fixed at 0.0.3
